### ISSUE TITLE
demo is broken due to https browser security policy

### ISSUE THREAD

**Issue by coolaj86** [silverbucket/webfinger.js#12]
github hosting is now https-only (yay!) but you've got lots of insecure links and requests and such, so your demo is broken

https://silverbucket.github.io/webfinger.js/demo/

**Comment by silverbucket** [comment]
Ah cool, thanks for pointing this out. Will update all links to https if possible.

**Comment by silverbucket** [comment]
Hmm, after having a look, it seems all the warnings i the browser are due to links provided within webfinger records (ie. an http URL for an avatar). I don't think there's anything I can do on the client end to address this, we have to handle the links as they are provided to us.

I did update the README to link to the HTTPS URL for the demo. I'll close this but feel free to re-open if I've missed something here.
