### ISSUE TITLE
isLocalhost behavior and HTTPS

### ISSUE THREAD

**Issue by fkooman** [silverbucket/webfinger.js#14]
We are running into an issue with Webfinger and remoteStorage where a Vagrant instance is (using port forwarding) running on `https://localhost:8443` and `http://localhost:8480`. The `isLocalhost` check recognizes this a being a localhost connection and then uses (always) HTTP. This does not work in this instance when using the identity `foo@localhost:8443`. 

Is/was there a reason to do this? Do you have any ideas on how to fix this?

Update: what was the rationale to have this `isLocalhost` check in the first place? Can it maybe be removed?

**Comment by silverbucket** [comment]
@fkooman Unfortunately I did not explain well enough in the comment message why I added that functionality.
https://github.com/silverbucket/webfinger.js/commit/ea64478cfc93a0323440cd8bae08777ecb91c9d4

I believe the reason I did it was to be able to use localhost by default with HTTP, instead of defaulting to HTTPS and having to fallback. Because most localhost development environments will not use SSL.

One work around is to use a different name and alias it to localhost (ie. `local.dev`)... If you have any other suggestion as to how the behavior might be improved let me know.

**Comment by silverbucket** [comment]
Maybe @skddc or @galfert remember?

**Comment by skddc** [comment]
Yes, it's exactly as you describe it. Also, we switched to using hostnames for the Vagrant machine anyway, so I guess @fkooman is also fine with this being closed.

**Comment by fkooman** [comment]
Yeah sure, I guess no longer relevant. It still bugs me somewhat that there is 'development' code in the 'production' flow :)
