### ISSUE TITLE
Neutral URI schema

### ISSUE THREAD

**Issue by vhpoet** [silverbucket/webfinger.js#18]
I'm trying to do a webfinger lookup using an `http` resource identifier `/.well-known/?resource=http://example.com/accounts/someone`, but webfinger.js [has a hardcoded acct:](https://github.com/silverbucket/webfinger.js/blob/master/src/webfinger.js#L240) while the [webfinger spec](https://tools.ietf.org/html/rfc7033#section-4.5) states that it's neutral regarding the scheme.

I would suggest adding the `acct:` only if the scheme is not specified.

**Comment by silverbucket** [comment]
Ah, good point, thanks for reporting that.

**Comment by silverbucket** [comment]
hi @vhpoet ... I just release a new version which should address this. please try it out and let me know if anything isn't working as expected.

**Comment by vhpoet** [comment]
@silverbucket thanks for a quick fix, but I'm not sure this is the right behavior. 

A lookup for 
`http://domain.com/accounts/alice` requests 
`https://domain.com/accounts/alice/.well-known/webfinger?resource=http://domain.com/accounts/alice` 

instead of 

`http://domain.com/.well-known/webfinger?resource=http://domain.com/accounts/alice`. 

Also note the http, https difference.

**Comment by silverbucket** [comment]
@vhpoet yeah, this is actually due to the spec. It enforces HTTPS. I've added a flag to optionally turn it off (used for development or special situations). 

https://github.com/silverbucket/webfinger.js#use

When you create a new WebFinger object, pass in { tls_only: false } as one of the config properties, and that should fix your problem.

**Comment by vhpoet** [comment]
ah ok, thanks for a quick fix @silverbucket !
